title: Mise - Open-source recipe manager
logo: docs/screenshots/01-recipe-list.png
description: Build your digital family cookbook. Store, share, and scale your favorite meals with a clean interface that stays out of your way.
show_downloads: true
google_analytics: G-X26FR5BV71
theme: jekyll-theme-minimal
